name: fyp_scaneat_cc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web: ^0.5.4+2
  image_picker: ^1.0.4
  flutter_barcode_sdk: ^2.2.8
  google_generative_ai: ^0.1.0
  flutter_markdown: ^0.6.18
  image: ^4.1.3
  geocoding: ^2.1.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
